import { Download } from "lucide-react";
import type { MissionReport as MissionReportData } from "../../types/api";

const OUTCOME_COLOR: Record<MissionReportData["outcome"], string> = {
    NOMINAL: "#7fe0a0",
    DEGRADED: "#eab308",
    FAILURE: "#e8543f",
    "NO HEALTH DATA": "#888",
};

const LEVEL_COLOR: Record<string, string> = {
    MONITOR: "#7fd4ff",
    CAUTION: "#eab308",
    WARNING: "#f97316",
    CRITICAL: "#e8543f",
    CLEARED: "#7fe0a0",
};

function clock(seconds: number | null | undefined): string {
    if (seconds == null) return "--";
    const m = Math.floor(seconds / 60);
    const s = Math.round(seconds % 60);
    return `T+${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
}

function toMarkdown(r: MissionReportData): string {
    const lines = [
        `# Mission health report — ${r.mission_id}`,
        "",
        `- **Engine:** ${r.engine_id}`,
        `- **Mission profile:** ${r.profile ?? "unknown"}`,
        `- **Start / end:** ${new Date(r.start_time).toLocaleString()} – ${new Date(r.end_time).toLocaleString()} (${clock(r.duration_s)})`,
        `- **Flight conditions:** up to ${r.max_altitude_m} m, ambient ${r.ambient_min_c}–${r.ambient_max_c} °C, mean throttle ${Math.round(r.mean_throttle * 100)} %`,
        "",
        "## Outcome",
        "",
        `- **Result:** ${r.outcome}${r.failure_at_s != null ? ` (failure threshold reached at ${clock(r.failure_at_s)})` : ""}`,
        `- **Final overall health:** ${r.final_health ?? "--"} / 100; lowest ${r.min_health ?? "--"} at ${clock(r.min_health_at_s)}`,
        `- **Weakest subsystem:** ${r.weakest_subsystem ?? "--"} (${r.weakest_subsystem_health ?? "--"} at ${clock(r.weakest_subsystem_at_s)})`,
        `- **Shortest predicted time to failure:** ${r.min_time_to_failure_s != null ? `${r.min_time_to_failure_s} s` : "none (no failure predicted)"}`,
        `- **Efficiency index:** mean ${r.efficiency_mean ?? "--"}, lowest ${r.efficiency_min ?? "--"} (100 = warmed-up healthy engine)`,
        "",
        "## Faults detected",
        "",
        ...(r.faults.length
            ? r.faults.map((f) => `- **${f.fault}:** first detected at ${clock(f.first_detected_at_s)}, present for ${f.seconds_detected} s`)
            : ["None."]),
        "",
        "## Advisory timeline",
        "",
        ...(r.advisories.length
            ? r.advisories.map((a) =>
                `- **${clock(a.at_s)} ${a.level}:** ${a.title}${a.eta_seconds != null ? ` (~${a.eta_seconds} s to failure)` : ""}${a.do_now.length ? `. ${a.do_now.join(" ")}` : ""}`)
            : ["No advisories issued."]),
        "",
        "## Maintenance actions before next flight",
        "",
        ...(r.maintenance.length ? r.maintenance.map((m) => `- [ ] ${m}`) : ["None required."]),
        "",
        "_Generated by the aero-piston engine digital twin. Prototype guidance, not certified procedures._",
        "",
    ];
    return lines.join("\n");
}

function download(report: MissionReportData) {
    const blob = new Blob([toMarkdown(report)], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${report.mission_id}_health_report.md`;
    link.click();
    URL.revokeObjectURL(url);
}

export default function MissionReport({ report }: { report: MissionReportData | null }) {
    const mono = { fontFamily: "'JetBrains Mono', monospace" };

    if (!report) return null;

    const cards = [
        {
            label: "OUTCOME",
            value: report.outcome,
            color: OUTCOME_COLOR[report.outcome],
            sub: report.failure_at_s != null ? `failure at ${clock(report.failure_at_s)}` : report.profile ?? "",
        },
        {
            label: "LOWEST HEALTH",
            value: report.min_health != null ? `${report.min_health} / 100` : "--",
            color: "#fff",
            sub: report.weakest_subsystem ? `weakest: ${report.weakest_subsystem} (${report.weakest_subsystem_health})` : "",
        },
        {
            label: "FAULTS DETECTED",
            value: report.faults.length ? report.faults.map((f) => f.fault).join(", ") : "None",
            color: report.faults.length ? "#eab308" : "#7fe0a0",
            sub: report.faults.length ? `first at ${clock(report.faults[0].first_detected_at_s)}` : "",
        },
        {
            label: "EFFICIENCY INDEX",
            value: report.efficiency_mean != null ? `${report.efficiency_mean}` : "--",
            color: "#fff",
            sub: report.efficiency_min != null ? `lowest ${report.efficiency_min} (healthy = 100)` : "",
        },
    ];

    return (
        <section className="mb-8 p-5" style={{ border: "1px solid #3a3a3a", background: "#0e0e0e" }}>
            <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
                <div>
                    <div className="text-xs mb-1" style={{ ...mono, color: "#C6FF3D" }}>
                        MISSION-WISE HEALTH REPORT
                    </div>
                    <h2 className="text-2xl font-bold" style={{ color: "#fff" }}>
                        {report.profile ?? "Mission"} — {clock(report.duration_s)}
                    </h2>
                </div>
                <button
                    onClick={() => download(report)}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-bold"
                    style={{ ...mono, background: "#C6FF3D", color: "#050505" }}
                >
                    <Download size={14} /> DOWNLOAD REPORT
                </button>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
                {cards.map((card) => (
                    <div key={card.label} className="p-3" style={{ border: "1px solid #2a2a2a" }}>
                        <div className="text-xs mb-1.5" style={{ ...mono, color: "#777" }}>{card.label}</div>
                        <div className="text-base font-bold" style={{ color: card.color }}>{card.value}</div>
                        {card.sub && <div className="text-xs mt-1" style={{ ...mono, color: "#999" }}>{card.sub}</div>}
                    </div>
                ))}
            </div>

            <div className="grid md:grid-cols-2 gap-5">
                <div>
                    <div className="text-xs mb-2 font-semibold" style={{ ...mono, color: "#c0c0c0" }}>ADVISORY TIMELINE</div>
                    {report.advisories.length === 0 ? (
                        <div className="text-sm" style={{ color: "#7fe0a0" }}>No advisories issued.</div>
                    ) : (
                        <ul className="flex flex-col gap-1.5 text-sm">
                            {report.advisories.map((a, i) => (
                                <li key={i} style={{ color: "#d8d8d8" }}>
                                    <span style={{ ...mono, color: "#888" }}>{clock(a.at_s)} </span>
                                    <span style={{ ...mono, color: LEVEL_COLOR[a.level] ?? "#fff", fontWeight: 700 }}>{a.level} </span>
                                    {a.title}
                                    {a.eta_seconds != null && <span style={{ color: "#999" }}> (~{a.eta_seconds} s to failure)</span>}
                                </li>
                            ))}
                        </ul>
                    )}
                </div>
                <div>
                    <div className="text-xs mb-2 font-semibold" style={{ ...mono, color: "#c0c0c0" }}>MAINTENANCE BEFORE NEXT FLIGHT</div>
                    {report.maintenance.length === 0 ? (
                        <div className="text-sm" style={{ color: "#7fe0a0" }}>None required.</div>
                    ) : (
                        <ul className="flex flex-col gap-1.5 text-sm" style={{ color: "#d8d8d8" }}>
                            {report.maintenance.map((m) => <li key={m}>☐ {m}</li>)}
                        </ul>
                    )}
                </div>
            </div>
        </section>
    );
}
