"""remove unused telemetry fields

Revision ID: 063319a65a67
Revises: 4f1b64de01fa
Create Date: 2026-09-03 21:26:56.721296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063319a65a67'
down_revision: Union[str, Sequence[str], None] = '4f1b64de01fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'battery_voltage')
    op.drop_column('telemetry', 'injection_timing')
    op.drop_column('telemetry', 'alternator_current')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('alternator_current', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('injection_timing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('battery_voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
