"""add torque to telemetry

Revision ID: 1f2e5c845254
Revises: d482a2992c87
Create Date: 2026-09-04 00:40:50.129545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2e5c845254'
down_revision: Union[str, Sequence[str], None] = 'd482a2992c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'telemetry',
        sa.Column(
            'torque',
            sa.Float(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE telemetry SET torque = 0 WHERE torque IS NULL"
    )

    op.alter_column(
        'telemetry',
        'torque',
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'torque')
    # ### end Alembic commands ###
