%% simulink_mqtt_publisher.m

clear;
clc;

model_name = 'AeroPistonEngineSimulator';

%% Load model and parameters

load_system(model_name);
engine_params;

%% Simulation settings

simulation_time = 1200;

% One telemetry message per simulated second
publish_interval = 1.0;

%% Simulation input

t = (0:0.1:simulation_time)';

u = [
    ones(size(t)), ...
    0.5 * ones(size(t)), ...
    zeros(size(t)), ...
    25 * ones(size(t))
];

%% Set fault

% 0 = Healthy
% 1 = Misfire

set_param([model_name '/Fault_ID'], 'Value', '0');

%% Run simulation

fprintf('Running Simulink...\n');

simOut = sim(model_name, ...
    'StopTime', num2str(simulation_time));

telemetry_log = simOut.telemetry_log;

fprintf('Simulation complete.\n');

%% Connect to MQTT

mqtt = py.importlib.import_module('paho.mqtt.client');

client = mqtt.Client();

client.connect( ...
    '127.0.0.1', ...
    int32(1883), ...
    int32(60));

fprintf('Connected to MQTT broker.\n');

%% Start MQTT network loop

client.loop_start();

%% Create publishing timeline

publish_time = (0:publish_interval:simulation_time)';

fprintf( ...
    'Publishing %d telemetry messages...\n', ...
    length(publish_time));

%% Base timestamp

% IMPORTANT:
% We do NOT add simulated seconds to the timestamp.
% The backend validates timestamps against real current time.

base_timestamp = datetime( ...
    '2025-01-01T00:00:00', ...
    'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss', ...
    'TimeZone', 'UTC');

%% MQTT topic

topic = 'engine/engine_001/telemetry';

%% Publish telemetry

for i = 1:length(publish_time)

    current_time = publish_time(i);

    %% Interpolate telemetry

    rpm = interp1( ...
        telemetry_log.signal1.Time, ...
        squeeze(telemetry_log.signal1.Data), ...
        current_time, ...
        'linear');

    fuel_flow = interp1( ...
        telemetry_log.signal2.Time, ...
        squeeze(telemetry_log.signal2.Data), ...
        current_time, ...
        'linear');

    oil_temperature = interp1( ...
        telemetry_log.signal4.Time, ...
        squeeze(telemetry_log.signal4.Data), ...
        current_time, ...
        'linear');

    oil_pressure = interp1( ...
        telemetry_log.signal5.Time, ...
        squeeze(telemetry_log.signal5.Data), ...
        current_time, ...
        'linear');

    cht = interp1( ...
        telemetry_log.signal6.Time, ...
        squeeze(telemetry_log.signal6.Data), ...
        current_time, ...
        'linear');

    egt = interp1( ...
        telemetry_log.signal8.Time, ...
        squeeze(telemetry_log.signal8.Data), ...
        current_time, ...
        'linear');

    vibration = interp1( ...
        telemetry_log.signal9.Time, ...
        squeeze(telemetry_log.signal9.Data), ...
        current_time, ...
        'linear');

    %% Generate timestamp

    % Use current real time.
    %
    % Add milliseconds so every telemetry event has
    % a unique timestamp even though we are publishing
    % much faster than real time.

    timestamp = base_timestamp + seconds(current_time);

    timestamp.Format = ...
        'yyyy-MM-dd''T''HH:mm:ss''Z''';

    %% Create JSON payload

    payload = sprintf([ ...
        '{"timestamp":"%s",' ...
        '"engine_id":"engine_001",' ...
        '"mission_id":"mission_001",' ...
        '"rpm":%.3f,' ...
        '"cht":%.3f,' ...
        '"egt":%.3f,' ...
        '"oil_pressure":%.3f,' ...
        '"oil_temperature":%.3f,' ...
        '"fuel_flow":%.3f,' ...
        '"vibration":%.3f}' ...
        ], ...
        char(timestamp), ...
        rpm, ...
        cht, ...
        egt, ...
        oil_pressure, ...
        oil_temperature, ...
        fuel_flow, ...
        vibration);

    %% Publish using QoS 1

    msg = client.publish( ...
        topic, ...
        payload, ...
        int32(1));

    %% Wait for MQTT publish confirmation

    msg.wait_for_publish();

    %% Progress output

    if mod(i, 10) == 0

        fprintf( ...
            'Published %d / %d messages (t = %.0f s)\n', ...
            i, ...
            length(publish_time), ...
            current_time);

    end

end

%% Allow backend to finish processing

fprintf('Waiting for backend to process messages...\n');

pause(5);

%% Stop MQTT loop

client.loop_stop();

%% Disconnect

client.disconnect();

%% Done

fprintf('\n');
fprintf('========================================\n');
fprintf('MQTT streaming complete.\n');
fprintf('Messages published: %d\n', length(publish_time));
fprintf('========================================\n');